/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/* eslint-disable @typescript-eslint/consistent-indexed-object-style */

export interface paths {
    "/analytics/downgrade-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Downgrades the specified user to Schej Free */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Payload"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/monthly-active-event-creators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets the daily count of monthly active event creators over a date range */
        get: {
            parameters: {
                query: {
                    /** @description Start date (YYYY-MM-DD) for the range */
                    startDate: string;
                    /** @description End date (YYYY-MM-DD) for the range */
                    endDate: string;
                    /** @description Client's timezone offset in minutes from UTC (e.g., -420 for UTC-7) */
                    timezoneOffset: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            count?: number;
                            date?: string;
                        }[];
                    };
                };
                /** @description Invalid date format, range, or timezone offset */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/monthly-active-event-creators-with-more-than-x-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets the daily count of monthly active event creators over a date range with more than x events */
        get: {
            parameters: {
                query: {
                    /** @description Start date (YYYY-MM-DD) for the range */
                    startDate: string;
                    /** @description End date (YYYY-MM-DD) for the range */
                    endDate: string;
                    /** @description Client's timezone offset in minutes from UTC (e.g., -420 for UTC-7) */
                    timezoneOffset: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            count?: number;
                            date?: string;
                        }[];
                    };
                };
                /** @description Invalid date format, range, or timezone offset */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/scanned-poster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Notifies us when poster QR code has been scanned */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the location that poster was scanned from and the url that was scanned */
            requestBody: {
                content: {
                    "application/json": {
                        location?: components["schemas"]["models.Location"];
                        url?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/upgrade-dialog-viewed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Notifies us when user has viewed the upgrade dialog */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the user id */
            requestBody: {
                content: {
                    "application/json": {
                        userId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/upgrade-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upgrades the specified user to Schej Premium */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Payload"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/user/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets the user by email */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User email */
                    email: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/check-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checks whether a user with the given email exists */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email to check */
            requestBody: {
                content: {
                    "application/json": {
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sends an OTP code to the given email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email to send OTP to */
            requestBody: {
                content: {
                    "application/json": {
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verifies an OTP code and signs the user in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email, OTP code, and timezone offset */
            requestBody: {
                content: {
                    "application/json": {
                        code?: string;
                        email?: string;
                        timezoneOffset?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signs user in
         * @description Signs user in and sets the access token session variable
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the Google authorization code, scope, calendar type, and the user's timezone offset */
            requestBody: {
                content: {
                    "application/json": {
                        calendarType?: string;
                        code?: string;
                        scope?: string;
                        timezoneOffset?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in-mobile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signs user in from mobile
         * @description Signs user in and sets the access token session variable
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the Google authorization code, calendar type, and the user's timezone offset */
            requestBody: {
                content: {
                    "application/json": {
                        accessToken?: string;
                        calendarType?: string;
                        expiresIn?: number;
                        idToken?: string;
                        refreshToken?: string;
                        scope?: string;
                        timezoneOffset?: number;
                        tokenOrigin?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signs user out
         * @description Signs user out and deletes the session
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets whether the user is signed in or not
         * @description Returns a 401 error if user is not signed in, 200 if they are
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error object */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a new event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing info about the event to create */
            requestBody: {
                content: {
                    "application/json": {
                        activeSlots?: string[];
                        attendees?: string[];
                        blindAvailabilityEnabled?: boolean;
                        dates?: string[];
                        daysOnly?: boolean;
                        duration?: number;
                        enabledSlots?: string[];
                        eventTimezone?: string;
                        isSignUpForm?: boolean;
                        name?: string;
                        notificationsEnabled?: boolean;
                        remindees?: string[];
                        sendEmailAfterXResponses?: number;
                        signUpBlocks?: components["schemas"]["models.SignUpBlock"][];
                        slotGeneration?: components["schemas"]["models.SlotGeneration"];
                        timeIncrement?: number;
                        timedRecurrence?: components["schemas"]["models.TimedRecurrence"];
                        type?: components["schemas"]["models.EventType"];
                        when2meetHref?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            eventId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets an event based on its id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Event"];
                    };
                };
            };
        };
        /** Edits an event based on its id */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            /** @description Object containing info about the event to update */
            requestBody: {
                content: {
                    "application/json": {
                        activeSlots?: string[];
                        attendees?: string[];
                        blindAvailabilityEnabled?: boolean;
                        dates?: string[];
                        daysOnly?: boolean;
                        description?: string;
                        duration?: number;
                        enabledSlots?: string[];
                        eventTimezone?: string;
                        name?: string;
                        notificationsEnabled?: boolean;
                        remindees?: string[];
                        sendEmailAfterXResponses?: number;
                        signUpBlocks?: components["schemas"]["models.SignUpBlock"][];
                        slotGeneration?: components["schemas"]["models.SlotGeneration"];
                        timeIncrement?: number;
                        timedRecurrence?: components["schemas"]["models.TimedRecurrence"];
                        type?: components["schemas"]["models.EventType"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Deletes an event based on its id */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive an event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            /** @description Archive status */
            requestBody: {
                content: {
                    "application/json": {
                        archive?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/calendar-availabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return a map mapping user id to their calendar events that they have enabled for the given time range */
        get: {
            parameters: {
                query: {
                    /** @description Lower bound for event's start time to filter by */
                    timeMin: string;
                    /** @description Upper bound for event's end time to filter by */
                    timeMax: string;
                };
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: {
                                [key: string]: components["schemas"]["calendar.CalendarEventsWithError"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline the current user's invite to the event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            /** @description Object containing options for the duplicated event */
            requestBody: {
                content: {
                    "application/json": {
                        copyAvailability?: boolean;
                        eventName?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolves an event identifier to both short and long IDs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event shortId or longId */
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            longId?: string;
                            shortId?: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["responses.Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/rename-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename a guest response */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            /** @description Object containing info about the guest response to rename */
            requestBody: {
                content: {
                    "application/json": {
                        newName?: string;
                        oldName?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Guest name already exists */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["responses.Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/responded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the user as having responded to this event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            /** @description Object containing the user's email */
            requestBody: {
                content: {
                    "application/json": {
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Updates the current user's availability */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            /** @description Object containing info about the event response to update */
            requestBody: {
                content: {
                    "application/json": {
                        availability?: string[];
                        calendarOptions?: components["schemas"]["models.CalendarOptions"];
                        enabledCalendars?: {
                            [key: string]: string[];
                        };
                        guest?: boolean;
                        ifNeeded?: string[];
                        manualAvailability?: {
                            [key: string]: string[];
                        };
                        name?: string;
                        signUpBlockIds?: string[];
                        useCalendarAvailability?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Delete the current user's availability */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            /** @description Object containing info about the event response to delete */
            requestBody: {
                content: {
                    "application/json": {
                        guest?: boolean;
                        name?: string;
                        userId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets responses for an event, filtering availability to be within the date ranges */
        get: {
            parameters: {
                query: {
                    /** @description Lower bound for start time to filter availability by */
                    timeMin: string;
                    /** @description Upper bound for end time to filter availability by */
                    timeMax: string;
                };
                header?: never;
                path: {
                    /** @description Event ID */
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: components["schemas"]["models.Response"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a Timeful event from a remote instance */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the URL of the remote event */
            requestBody: {
                content: {
                    "application/json": {
                        url?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            eventId?: string;
                            shortId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slackbot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gets the number of signed up users */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Text response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["commands.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deletes the currently signed in user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/add-apple-calendar-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adds an apple calendar account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the email and app password of the apple account */
            requestBody: {
                content: {
                    "application/json": {
                        email?: string;
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/add-google-calendar-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adds a new calendar account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the Google authorization code and scope */
            requestBody: {
                content: {
                    "application/json": {
                        code?: string;
                        scope?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/add-ics-calendar-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adds an ICS calendar account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the feed URL and label of the ICS calendar */
            requestBody: {
                content: {
                    "application/json": {
                        feedUrl?: string;
                        label?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/add-outlook-calendar-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adds a new outlook calendar account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the Outlook authorization code and scope */
            requestBody: {
                content: {
                    "application/json": {
                        code?: string;
                        scope?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/calendar-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Updates the user's calendar options */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the updated options */
            requestBody: {
                content: {
                    "application/json": {
                        bufferTime?: components["schemas"]["models.BufferTimeOptions"];
                        workingHours?: components["schemas"]["models.WorkingHoursOptions"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/user/calendars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets the user's calendar events
         * @description Gets the user's calendar events between "timeMin" and "timeMax"
         */
        get: {
            parameters: {
                query: {
                    /** @description Lower bound for event's start time to filter by */
                    timeMin: string;
                    /** @description Upper bound for event's end time to filter by */
                    timeMax: string;
                    /** @description Comma separated list of accounts to fetch calendar events from */
                    accounts?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: components["schemas"]["calendar.CalendarEventsWithError"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets all the user's events
         * @description Returns an array containing all the user's events
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Event"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/events/{eventId}/set-folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sets the folder for the specified event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the event to set the folder for */
                    eventId: string;
                };
                cookie?: never;
            };
            /** @description The ID of the folder to set the event to */
            requestBody: {
                content: {
                    "application/json": {
                        folderId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all folders */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of all folders for the user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Folder"][];
                    };
                };
                /** @description Invalid user ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Failed to get folders */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a new folder */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Folder name and optional color */
            requestBody: {
                content: {
                    "application/json": {
                        color?: string;
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description The ID of the created folder */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["routes.CreateFolderResponse"];
                    };
                };
                /** @description Invalid user ID or request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Failed to create folder */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/folders/{folderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a folder by its ID and its contents */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Folder ID */
                    folderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The folder object with events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Folder"];
                    };
                };
                /** @description Invalid user ID or folder ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Folder not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Failed to get events in folder */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a folder */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Folder ID */
                    folderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid user ID or folder ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Failed to delete folder */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a folder's name or color */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Folder ID */
                    folderId: string;
                };
                cookie?: never;
            };
            /** @description New folder name and/or color */
            requestBody: {
                content: {
                    "application/json": {
                        color?: string;
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid user ID or folder ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Failed to update folder */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/user/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Updates the user's name */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the updated name */
            requestBody: {
                content: {
                    "application/json": {
                        firstName?: string;
                        lastName?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets the user's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A user profile object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/remove-calendar-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes an existing calendar account */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Object containing the email + type of the calendar account to remove */
            requestBody: {
                content: {
                    "application/json": {
                        calendarType?: components["schemas"]["models.CalendarType"];
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/searchContacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Searches the user's contacts based on the given query */
        get: {
            parameters: {
                query: {
                    /** @description Query to search for */
                    query: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.User"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/toggle-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggles whether the specified calendar is enabled or disabled for the user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email of calendar account and whether to enable it */
            requestBody: {
                content: {
                    "application/json": {
                        calendarAccountKey?: string;
                        enabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/toggle-sub-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggles whether the specified sub-calendar is enabled or disabled for the user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email of calendar account, the sub calendar id, and whether to enable it */
            requestBody: {
                content: {
                    "application/json": {
                        calendarAccountKey?: string;
                        enabled?: boolean;
                        subCalendarId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a minimal public user profile (safe for unauthenticated clients) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/is-premium": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns whether the given user is a premium user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            isPremium?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "bson.M": {
            [key: string]: unknown;
        };
        "calendar.CalendarEventsWithError": {
            calendarEvents?: components["schemas"]["models.CalendarEvent"][];
            error?: unknown;
        };
        "commands.Response": {
            blocks?: components["schemas"]["bson.M"][];
            /** @description ephemeral or in_channel */
            response_type?: string;
            text?: string;
        };
        "models.AppleCalendarAuth": Record<string, never>;
        "models.Attendee": {
            _id?: string;
            declined?: boolean;
            email?: string;
            eventId?: string;
        };
        "models.BufferTimeOptions": {
            enabled?: boolean;
            time?: number;
        };
        "models.CalendarAccount": {
            appleCalendarAuth?: components["schemas"]["models.AppleCalendarAuth"];
            calendarType?: components["schemas"]["models.CalendarType"];
            /** @description Email is required for all calendar accounts */
            email?: string;
            enabled?: boolean;
            icsCalendarAuth?: components["schemas"]["models.ICSCalendarAuth"];
            oAuth2CalendarAuth?: components["schemas"]["models.OAuth2CalendarAuth"];
            picture?: string;
            subCalendars?: {
                [key: string]: components["schemas"]["models.SubCalendar"];
            };
        };
        "models.CalendarEvent": {
            /** @description Whether the event is an all day event */
            allDay?: boolean;
            calendarId?: string;
            endDate?: number;
            /** @description Whether the user is free during this event */
            free?: boolean;
            id?: string;
            startDate?: number;
            summary?: string;
        };
        "models.CalendarOptions": {
            bufferTime?: components["schemas"]["models.BufferTimeOptions"];
            workingHours?: components["schemas"]["models.WorkingHoursOptions"];
        };
        /** @enum {string} */
        "models.CalendarType": "apple" | "google" | "outlook" | "ics";
        "models.Event": {
            _id?: string;
            activeSlots?: number[];
            /** @description Attendees for an availability group (fetched from Attendees collection) */
            attendees?: components["schemas"]["models.Attendee"][];
            /** @description Whether to enable blind availability */
            blindAvailabilityEnabled?: boolean;
            calendarEventId?: string;
            collectEmails?: boolean;
            /** @description PostHog ID for the event creator */
            creatorPosthogId?: string;
            dates?: number[];
            /** @description Whether to only poll for days, not times */
            daysOnly?: boolean;
            description?: string;
            duration?: number;
            enabledSlots?: number[];
            eventTimezone?: string;
            /** @description Whether the user has responded to the availability group (fetched based on whether user is in Attendees) */
            hasResponded?: boolean;
            /** @description Used for specific times for specific dates feature */
            hasSpecificTimes?: boolean;
            isArchived?: boolean;
            isDeleted?: boolean;
            /** @description Sign up form details */
            isSignUpForm?: boolean;
            name?: string;
            notificationsEnabled?: boolean;
            /** @description Used to store the number of responses for the event */
            numResponses?: number;
            ownerId?: string;
            /** @description Remindees */
            remindees?: components["schemas"]["models.Remindee"][];
            /** @description Availability responses - old format for backward compatibility (fetched from eventResponses collection) */
            responses?: {
                [key: string]: components["schemas"]["models.Response"];
            };
            /** @description Scheduled event */
            scheduledEvent?: components["schemas"]["models.CalendarEvent"];
            sendEmailAfterXResponses?: number;
            shortId?: string;
            signUpBlocks?: components["schemas"]["models.SignUpBlock"][];
            signUpResponses?: {
                [key: string]: components["schemas"]["models.SignUpResponse"];
            };
            slotGeneration?: components["schemas"]["models.SlotGeneration"];
            /** @description Whether to start the event on Monday (as opposed to Sunday, used for DOW events) */
            startOnMonday?: boolean;
            timeIncrement?: number;
            timedRecurrence?: components["schemas"]["models.TimedRecurrence"];
            times?: number[];
            type?: components["schemas"]["models.EventType"];
            when2meetHref?: string;
        };
        /** @enum {string} */
        "models.EventType": "specific_dates" | "dow" | "group";
        "models.Folder": {
            _id?: string;
            color?: string;
            eventIds?: string[];
            isDeleted?: boolean;
            name?: string;
            userId?: string;
        };
        "models.ICSCalendarAuth": {
            label?: string;
        };
        "models.Location": {
            city?: string;
            country_code?: string;
            country_name?: string;
            latitude?: number;
            longitude?: number;
            postal?: string;
            state?: string;
        };
        "models.OAuth2CalendarAuth": Record<string, never>;
        "models.Remindee": {
            email?: string;
            responded?: boolean;
        };
        "models.Response": {
            /** @description Availability */
            availability?: number[];
            calendarOptions?: components["schemas"]["models.CalendarOptions"];
            email?: string;
            /** @description Maps email to an array of sub calendar ids */
            enabledCalendars?: {
                [key: string]: string[];
            };
            guestEditPolicy?: string;
            guestId?: string;
            guestOwnershipMode?: string;
            ifNeeded?: number[];
            /** @description Mapping from the start date of a day to the available times for that day */
            manualAvailability?: {
                [key: string]: number[];
            };
            /** @description Guest information */
            name?: string;
            /** @description Calendar availability variables for Availability Groups feature */
            useCalendarAvailability?: boolean;
            user?: components["schemas"]["models.User"];
            /** @description User information */
            userId?: string;
        };
        "models.SignUpBlock": {
            _id?: string;
            capacity?: number;
            endDate?: number;
            name?: string;
            startDate?: number;
        };
        "models.SignUpResponse": {
            email?: string;
            /** @description Guest information */
            name?: string;
            /** @description The IDs of the sign up blocks that the user has signed up for */
            signUpBlockIds?: string[];
            user?: components["schemas"]["models.User"];
            /** @description User information */
            userId?: string;
        };
        "models.SlotGeneration": {
            endTimeLocal?: string;
            startTimeLocal?: string;
            timeIncrementMinutes?: number;
        };
        "models.SubCalendar": {
            enabled?: boolean;
            name?: string;
        };
        "models.TimedRecurrence": {
            kind?: string;
            selectedDays?: string[];
            selectedDaysOfWeek?: number[];
            startOnMonday?: boolean;
        };
        "models.User": {
            /** @description Profile info */
            _id?: string;
            /**
             * @description CalendarAccounts is a mapping from {`email_CALENDARTYPE` => CalendarAccount} that contains all the
             *     additional accounts the user wants to see google calendar events for
             */
            calendarAccounts?: {
                [key: string]: components["schemas"]["models.CalendarAccount"];
            };
            /** @description Calendar options */
            calendarOptions?: components["schemas"]["models.CalendarOptions"];
            email?: string;
            firstName?: string;
            /** @description Whether the user has set a custom name for themselves, i.e. don't change their name when they sign in */
            hasCustomName?: boolean;
            isPremium?: boolean;
            lastName?: string;
            numEventsCreated?: number;
            picture?: string;
            /** @description The calendarAccountKey of the account the user first signed in with */
            primaryAccountKey?: string;
            /** @description Stripe customer ID */
            stripeCustomerId?: string;
            timezoneOffset?: number;
        };
        "models.WorkingHoursOptions": {
            enabled?: boolean;
            endTime?: number;
            startTime?: number;
        };
        "responses.Error": {
            error: unknown;
        };
        "routes.CreateFolderResponse": {
            id?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description Object containing the user email */
        Payload: {
            content: {
                "application/json": {
                    email?: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
